from stations import all_stations

station_list = all_stations[:,0]
station_list.sort()

next_stops = {key: [] for key in station_list}

try:
    next_stops["Acton Town"] = {"district": ["Chiswick Park", "Ealing Common"], "piccadilly": ["South Ealing", "Turnham Green", "Hammersmith (Dist&Picc Line)", "Ealing Common"]}
    next_stops["Aldgate"] = {"circle": ["Tower Hill", "Liverpool Street"], "metropolitan": ["Liverpool Street"]}
    next_stops["Aldgate East"] = {"district": ["Whitechapel", "Tower Hill"], "hammersmith-city": ["Whitechapel", "Liverpool Street"]}
    next_stops["Alperton"] = {"piccadilly": ["Sudbury Town", "Park Royal"]}
    next_stops["Amersham"] = {"metropolitan": ["Chalfont & Latimer"]}
    next_stops["Angel"] = {"northern": ["Old Street", "King's Cross St. Pancras"]}
    next_stops["Archway"] = {"northern": ["Highgate", "Tufnell Park"]}
    next_stops["Arnos Grove"] = {"piccadilly": ["Southgate", "Bounds Green"]}
    next_stops["Arsenal"] = {"piccadilly": ["Holloway Road", "Finsbury Park"]}
    next_stops["Baker Street"] = {"bakerloo": ["Regent's Park", "Marylebone"], "circle": ["Great Portland Street", "Edgware Road (Circle Line)"], "hammersmith-city": ["Great Portland Street", "Edgware Road (Circle Line)"], "jubilee": ["Bond Street", "St. John's Wood"], "metropolitan": ["Finchley Road", "Great Portland Street"]}
    next_stops["Balham"] = {"northern": ["Tooting Bec", "Clapham South"]}
    next_stops["Bank"] = {"central": ["Liverpool Street", "St. Paul's"], "northern": ["Moorgate", "London Bridge"], "waterloo-city": ["Waterloo"]}
    next_stops["Barbican"] = {"circle": ["Farringdon", "Moorgate"], "metropolitan": ["Farringdon", "Moorgate"], "hammersmith-city": ["Farringdon", "Moorgate"]}
    next_stops["Barking"] = {"district": ["East Ham", "Upney"], "hammersmith-city": ["East Ham"]}
    next_stops["Barkingside"] = {"central": ["Fairlop", "Newbury Park"]}
    next_stops["Barons Court"] = {"district": ["Hammersmith", "West Kensington"], "piccadilly": ["Hammersmith", "Earl's Court"]}
    next_stops["Battersea Power Station"] = {"northern": ["Nine Elms"]}
    next_stops["Bayswater"] = {"district": ["Notting Hill Gate", "Paddington"], "circle": ["Notting Hill Gate", "Paddington"]}
    next_stops["Becontree"] = {"district": ["Upney", "Dagenham Heathway"]}
    next_stops["Belsize Park"] = {"northern": ["Chalk Farm", "Hampstead"]}
    next_stops["Bermondsey"] = {"jubilee": ["Canada Water", "London Bridge"]}
    next_stops["Bethnal Green"] = {"central": ["Mile End", "Liverpool Street"]}
    next_stops["Blackfriars"] = {"circle": ["Mansion House", "Temple"], "district": ["Mansion House", "Temple"]}
    next_stops["Blackhorse Road"] = {"victoria": ["Tottenham Hale", "Walthamstow Central"]}
    next_stops["Bond Street"] = {"central": ["Marble Arch", "Oxford Circus"], "jubilee": ["Marble Arch", "Oxford Circus"]}
    next_stops["Borough"] = {"northern": ["London Bridge", "Elephant & Castle"]}
    next_stops["Boston Manor"] = {"piccadilly": ["Osterley", "Northfields"]}
    next_stops["Bounds Green"] = {"piccadilly": ["Wood Green", "Arnos Grove"]}
    next_stops["Bow Road"] = {"district": ["Mile End", "Bromley-by-Bow"], "hammersmith-city": ["Mile End", "Bromley-by-Bow"]}
    next_stops["Brent Cross"] = {"northern": ["Golders Green", "Hendon Central"]}
    next_stops["Brixton"] = {"victoria": ["Stockwell"]}
    next_stops["Bromley-by-Bow"] = {"district": ["West Ham", "Bow Road"], "hammersmith-city": ["West Ham", "Bow Road"]}
    next_stops["Buckhurst Hill"] = {"central": ["Loughton", "Woodford"]}
    next_stops["Burnt Oak"] = {"northern": ["Colindale", "Edgware"]}
    next_stops["Caledonian Road"] = {"piccadilly": ["Holloway Road", "King's Cross St. Pancras"]}
    next_stops["Camden Town"] = {"northern": ["Chalk Farm", "Euston", "Kentish Town", "Mornington Crescent"]}
    next_stops["Canada Water"] = {"jubilee": ["Bermondsey", "Canary Wharf"]}
    next_stops["Canary Wharf"] = {"jubilee": ["North Greenwich", "Canada Water"]}
    next_stops["Canning Town"] = {"jubilee": ["West Ham", "North Greenwich"]}
    next_stops["Cannon Street"] = {"circle": ["Mansion House", "Monument"], "district": ["Mansion House", "Monument"]}
    next_stops["Canons Park"] = {"jubilee": ["Queensbury", "Stanmore"]}
    next_stops["Chalfont & Latimer"] = {"metropolitan": ["Chorleywood", "Amersham", "Chesham"]}
    next_stops["Chalk Farm"] = {"northern": ["Camden Town", "Belsize Park"]}
    next_stops["Chancery Lane"] = {"central": ["St. Paul's", "Holborn"]}
    next_stops["Charing Cross"] = {"bakerloo": ["Embankment", "Piccadilly Circus"], "northern": ["Embankment", "Leicester Square"]}
    next_stops["Chesham"] = {"metropolitan": ["Chalfont & Latimer"]}
    next_stops["Chigwell"] = {"central": ["Roding Valley", "Grange Hill"]}
    next_stops["Chiswick Park"] = {"district": ["Acton Town", "Turnham Green"]}
    next_stops["Chorleywood"] = {"metropolitan": ["Chalfont & Latimer", "Rickmansworth"]}
    next_stops["Clapham Common"] = {"northern": ["Clapham South", "Clapham North"]}
    next_stops["Clapham North"] = {"northern": ["Stockwell", "Clapham Common"]}
    next_stops["Clapham South"] = {"northern": ["Balham", "Clapham Common"]}
    next_stops["Cockfosters"] = {"piccadilly": ["Oakwood"]}
    next_stops["Colindale"] = {"northern": ["Hendon Central", "Burnt Oak"]}
    next_stops["Colliers Wood"] = {"northern": ["South Wimbledon", "Tooting Broadway"]}
    next_stops["Covent Garden"] = {"piccadilly": ["Leicester Square", "Holborn"]}
    next_stops["Croxley"] = {"metropolitan": ["Moor Park", "Watford"]}
    next_stops["Dagenham East"] = {"district": ["Elm Park", "Dagenham Heathway"]}
    next_stops["Dagenham Heathway"] = {"district": ["Becontree", "Dagenham East"]}
    next_stops["Debden"] = {"central": ["Loughton", "Theydon Bois"]}
    next_stops["Dollis Hill"] = {"jubilee": ["Willesden Green", "Neasden"]}
    next_stops["Ealing Broadway"] = {"district": ["Ealing Common"], "central": ["West Acton"]}
    next_stops["Ealing Common"] = {"district": ["Acton Town", "Ealing Broadway"], "piccadilly": ["Acton Town", "North Ealing"]}
    next_stops["Earl's Court"] = {"district": ["Gloucester Road", "West Brompton", "High Street Kensington", "Kensington (Olympia)", "West Kensington"], "piccadilly": ["Gloucester Road", "Barons Court"]}
    next_stops["East Acton"] = {"central": ["White City", "North Acton"]}
    next_stops["East Finchley"] = {"northern": ["Highgate", "Finchley Central"]}
    next_stops["East Ham"] = {"district": ["Upton Park", "Barking"], "hammersmith-city": ["Upton Park", "Barking"]}
    next_stops["East Putney"] = {"district": ["Southfields", "Putney Bridge"]}
    next_stops["Eastcote"] = {"metropolitan": ["Ruislip Manor", "Rayners Lane"], "piccadilly": ["Ruislip Manor", "Rayners Lane"]}
    next_stops["Edgware"] = {"northern": ["Burnt Oak"]}
    next_stops["Edgware Road (Bakerloo)"] = {"bakerloo": ["Paddington", "Marylebone"]}
    next_stops["Edgware Road (Circle Line)"] = {"circle": ["Paddington", "Baker Street", "Paddington (H&C Line)"], "district": ["Paddington"], "hammersmith-city": ["Paddington (H&C Line)", "Baker Street"]}
    next_stops["Elephant & Castle"] = {"bakerloo": ["Lambeth North"], "northern": ["Borough", "Kennington"]}
    next_stops["Elm Park"] = {"district": ["Hornchurch", "Dagenham East"]}
    next_stops["Embankment"] = {"bakerloo": ["Charing Cross", "Waterloo"], "circle": ["Temple", "Westminster"], "district": ["Temple", "Westminster"], "northern": ["Charing Cross", "Waterloo"]}
    next_stops["Epping"] = {"central": ["Theydon Bois"]}
    next_stops["Euston"] = {"northern": ["King's Cross St. Pancras", "Warren Street", "Mornington Crescent", "Camden Town"], "victoria": ["King's Cross St. Pancras", "Warren Street"]}
    next_stops["Euston Square"] = {"circle": ["Great Portland Street", "King's Cross St. Pancras"], "hammersmith-city": ["Great Portland Street", "King's Cross St. Pancras"], "metropolitan": ["Great Portland Street", "King's Cross St. Pancras"]}
    next_stops["Fairlop"] = {"central": ["Hainault", "Grange Hill"]}
    next_stops["Farringdon"] = {"circle": ["Barbican", "King's Cross St. Pancras"], "hammersmith-city": ["Barbican", "King's Cross St. Pancras"], "metropolitan": ["Barbican", "King's Cross St. Pancras"]}
    next_stops["Finchley Central"] = {"northern": ["East Finchley", "West Finchley", "Mill Hill East"]}
    next_stops["Finchley Road"] = {"jubilee": ["Swiss Cottage", "West Hampstead"], "metropolitan": ["Wembley Park", "Baker Street"]}
    next_stops["Finsbury Park"] = {"piccadilly": ["Arsenal", "Manor House"], "victoria": ["Seven Sisters", "Highbury & Islington"]}
    next_stops["Fulham Broadway"] = {"district": ["Parsons Green", "West Brompton"]}
    next_stops["Gants Hill"] = {"central": ["Newbury Park", "Redbridge"]}
    next_stops["Gloucester Road"] = {"circle": ["High Street Kensington", "South Kensington"], "district": ["Earl's Court", "South Kensington"], "piccadilly": ["South Kensington", "Earl's Court"]}
    next_stops["Golders Green"] = {"northern": ["Brent Cross", "Hampstead"]}
    next_stops["Goldhawk Road"] = {"circle": ["Shepherd's Bush Market", "Hammersmith (H&C Line)"], "hammersmith-city": ["Shepherd's Bush Market", "Hammersmith (H&C Line)"]}
    next_stops["Goodge Street"] = {"northern": ["Warren Street", "Tottenham Court Road"]}
    next_stops["Grange Hill"] = {"central": ["Chigwell", "Hainault"]}
    next_stops["Great Portland Street"] = {"circle": ["Euston Square", "Baker Street"], "hammersmith-city": ["Euston Square", "Baker Street"], "metropolitan": ["Euston Square", "Baker Street"]}
    next_stops["Green Park"] = {"jubilee": ["Westminster", "Bond Street"], "victoria": ["Victoria", "Oxford Circus"], "piccadilly": ["Piccadilly Circus", "Hyde Park Corner"]}
    next_stops["Greenford"] = {"central": ["Northolt", "Perivale"]}
    next_stops["Gunnersbury"] = {"district": ["Kew Gardens", "Turnham Green"]}
    next_stops["Hainault"] = {"central": ["Fairlop", "Grange Hill"]}
    next_stops["Hammersmith (Dist&Picc Line)"] = {"district": ["Barons Court", "Ravenscourt Park"], "piccadilly": ["Barons Court", "Turnham Green", "Acton Town"]}
    next_stops["Hammersmith (H&C Line)"] = {"circle": ["Goldhawk Road"], "hammersmith-city": ["Goldhawk Road"]}
    next_stops["Hampstead"] = {"northern": ["Belsize Park", "Golders Green"]}
    next_stops["Hanger Lane"] = {"central": ["Perivale", "North Acton"]}
    next_stops["Harlesden"] = {"bakerloo": ["Willesden Junction", "Stonebridge Park"]}
    next_stops["Harrow & Wealdstone"] = {"bakerloo": ["Kenton"]}
    next_stops["Harrow-on-the-Hill"] = {"metropolitan": ["Northwick Park", "North Harrow", "West Harrow", "Moor Park", "Wembley Park"]}
    next_stops["Hatton Cross"] = {"piccadilly": ["Heathrow Terminals 2 & 3", "Hounslow West", "Heathrow Terminal 4"]}
    next_stops["Heathrow Terminal 4"] = {"piccadilly": ["Heathrow Terminals 2 & 3"]}
    next_stops["Heathrow Terminals 2 & 3"] = {"piccadilly": ["Hatton Cross", "Heathrow Terminal 5"]}
    next_stops["Heathrow Terminal 5"] = {"piccadilly": ["Heathrow Terminals 2 & 3"]}
    next_stops["Hendon Central"] = {"northern": ["Colindale", "Brent Cross"]}
    next_stops["High Barnet"] = {"northern": ["Totteridge & Whetstone"]}
    next_stops["High Street Kensington"] = {"district": ["Notting Hill Gate", "Earl's Court"], "circle": ["Notting Hill Gate", "Gloucester Road"]}
    next_stops["Highbury & Islington"] = {"victoria": ["Finsbury Park", "King's Cross St. Pancras"]}
    next_stops["Highgate"] = {"northern": ["East Finchley", "Archway"]}
    next_stops["Hillingdon"] = {"metropolitan": ["Ickenham", "Uxbridge"], "piccadilly": ["Ickenham", "Uxbridge"]}
    next_stops["Holborn"] = {"central": ["Tottenham Court Road", "Chancery Lane"], "piccadilly": ["Covent Garden", "Russell Square"]}
    next_stops["Holland Park"] = {"central": ["Notting Hill Gate", "Shepherd's Bush (Central)"]}
    next_stops["Holloway Road"] = {"piccadilly": ["Caledonian Road", "Arsenal"]}
    next_stops["Hornchurch"] = {"district": ["Elm Park", "Upminster Bridge"]}
    next_stops["Hounslow Central"] = {"piccadilly": ["Hounslow East", "Hounslow West"]}
    next_stops["Hounslow East"] = {"piccadilly": ["Osterley", "Hounslow Central"]}
    next_stops["Hounslow West"] = {"piccadilly": ["Hatton Cross", "Hounslow Central"]}
    next_stops["Hyde Park Corner"] = {"piccadilly": ["Knightsbridge", "Green Park"]}
    next_stops["Ickenham"] = {"metropolitan": ["Hillingdon", "Ruislip"], "piccadilly": ["Hillingdon", "Ruislip"]}
    next_stops["Kennington"] = {"northern": ["Elephant & Castle", "Oval", "Waterloo", "Nine Elms"]}
    next_stops["Kensal Green"] = {"bakerloo": ["Queen's Park", "Willesden Junction"]}
    next_stops["Kensington (Olympia)"] = {"district": ["Earl's Court"]}
    next_stops["Kentish Town"] = {"northern": ["Camden Town", "Tufnell Park"]}
    next_stops["Kenton"] = {"bakerloo": ["South Kenton", "Harrow & Wealdstone"]}
    next_stops["Kew Gardens"] = {"district": ["Gunnersbury", "Richmond"]}
    next_stops["Kilburn"] = {"jubilee": ["Willesden Green", "West Hampstead"]}
    next_stops["Kilburn Park"] = {"bakerloo": ["Maida Vale", "Queen's Park"]}
    next_stops["King's Cross St. Pancras"] = {"northern": ["Angel", "Euston"], "piccadilly": ["Russell Square", "Caledonian Road"], "victoria": ["Euston", "Highbury & Islington"], "metropolitan": ["Euston Square", "Farringdon"], "circle": ["Euston Square", "Farringdon"], "hammersmith-city": ["Euston Square", "Farringdon"]}
    next_stops["Kingsbury"] = {"jubilee": ["Wembley Park", "Queensbury"]}
    next_stops["Knightsbridge"] = {"piccadilly": ["South Kensington", "Hyde Park Corner"]}
    next_stops["Ladbroke Grove"] = {"circle": ["Latimer Road", "Westbourne Park"], "hammersmith-city": ["Latimer Road", "Westbourne Park"]}
    next_stops["Lambeth North"] = {"bakerloo": ["Elephant & Castle", "Waterloo"]}
    next_stops["Lancaster Gate"] = {"central": ["Marble Arch", "Queensway"]}
    next_stops["Latimer Road"] = {"circle": ["Ladbroke Grove", "Wood Lane"], "hammersmith-city": ["Ladbroke Grove", "Wood Lane"]}
    next_stops["Leicester Square"] = {"northern": ["Tottenham Court Road", "Charing Cross"], "piccadilly": ["Piccadilly Circus", "Covent Garden"]}
    next_stops["Leyton"] = {"central": ["Leytonstone", "Stratford"]}
    next_stops["Leytonstone"] = {"central": ["Leyton", "Snaresbrook", "Wanstead"]}
    next_stops["Liverpool Street"] = {"central": ["Bethnal Green", "Bank"], "circle": ["Aldgate", "Moorgate"], "hammersmith-city": ["Aldgate East", "Moorgate"], "metropolitan": ["Moorgate", "Aldgate"]}
    next_stops["London Bridge"] = {"northern": ["Borough", "Bank"], "jubilee": ["Southwark", "Bermondsey"]}
    next_stops["Loughton"] = {"central": ["Debden", "Buckhurst Hill"]}
    next_stops["Maida Vale"] = {"bakerloo": ["Warwick Avenue", "Kilburn Park"]}
    next_stops["Manor House"] = {"piccadilly": ["Turnpike Lane", "Finsbury Park"]}
    next_stops["Mansion House"] = {"circle": ["Cannon Street", "Blackfriars"], "district": ["Cannon Street", "Blackfriars"]}
    next_stops["Marble Arch"] = {"central": ["Bond Street", "Lancaster Gate"]}
    next_stops["Marylebone"] = {"bakerloo": ["Baker Street", "Edgware Road (Bakerloo)"]}
    next_stops["Mile End"] = {"central": ["Stratford", "Bethnal Green"], "district": ["Bow Road", "Stepney Green"], "hammersmith-city": ["Bow Road", "Stepney Green"]}
    next_stops["Mill Hill East"] = {"northern": ["Finchley Central"]}
    next_stops["Monument"] = {"circle": ["Cannon Street", "Tower Hill"], "district": ["Cannon Street", "Tower Hill"]}
    next_stops["Moor Park"] = {"metropolitan": ["Croxley", "Northwood", "Harrow-on-the-Hill", "Rickmansworth"]}
    next_stops["Moorgate"] = {"circle": ["Barbican", "Liverpool Street"], "hammersmith-city": ["Barbican", "Liverpool Street"], "metropolitan": ["Barbican", "Liverpool Street"], "northern": ["Old Street", "Bank"]}
    next_stops["Morden"] = {"northern": ["South Wimbledon"]}
    next_stops["Mornington Crescent"] = {"northern": ["Camden Town", "Euston"]}
    next_stops["Neasden"] = {"jubilee": ["Willesden Green", "Dollis Hill"]}
    next_stops["Newbury Park"] = {"central": ["Gants Hill", "Barkingside"]}
    next_stops["Nine Elms"] = {"northern": ["Battersea Power Station", "Kennington"]}
    next_stops["North Acton"] = {"central": ["East Acton", "Hanger Lane", "West Acton"]}
    next_stops["North Ealing"] = {"piccadilly": ["Park Royal", "Ealing Common"]}
    next_stops["North Greenwich"] = {"jubilee": ["Canning Town", "Canary Wharf"]}
    next_stops["North Harrow"] = {"metropolitan": ["Pinner", "Harrow-on-the-Hill"]}
    next_stops["North Wembley"] = {"bakerloo": ["South Kenton", "Wembley Central"]}
    next_stops["Northfields"] = {"piccadilly": ["South Ealing", "Boston Manor"]}
    next_stops["Northolt"] = {"central": ["Greenford", "South Ruislip"]}
    next_stops["Northwick Park"] = {"metropolitan": ["Preston Road", "Harrow-on-the-Hill"]}
    next_stops["Northwood"] = {"metropolitan": ["Moor Park", "Northwood Hills"]}
    next_stops["Northwood Hills"] = {"metropolitan": ["Northwood", "Pinner"]}
    next_stops["Notting Hill Gate"] = {"central": ["Queensway", "Holland Park"], "circle": ["Queensway", "High Street Kensington"], "district": ["Queensway", "High Street Kensington"]}
    next_stops["Oakwood"] = {"piccadilly": ["Cockfosters", "Southgate"]}
    next_stops["Old Street"] = {"northern": ["Moorgate", "Angel"]}
    next_stops["Osterley"] = {"piccadilly": ["Boston Manor", "Hounslow East"]}
    next_stops["Oval"] = {"northern": ["Stockwell", "Kennington"]}
    next_stops["Oxford Circus"] = {"bakerloo": ["Regent's Park", "Piccadilly Circus"], "central": ["Tottenham Court Road", "Bond Street"], "victoria": ["Warren Street", "Green Park"]}
    next_stops["Paddington"] = {"bakerloo": ["Edgware Road (Bakerloo)", "Warwick Avenue"], "circle": ["Edgware Road (Circle Line)", "Bayswater"], "district": ["Bayswater", "Edgware Road (Circle Line)"]}
    next_stops["Paddington (H&C Line)"] = {"circle": ["Edgware Road (Circle Line)", "Royal Oak"], "hammersmith-city": ["Royal Oak", "Baker Street"]}
    next_stops["Park Royal"] = {"piccadilly": ["North Ealing", "Alperton"]}
    next_stops["Parsons Green"] = {"district": ["Putney Bridge", "Fulham Broadway"]}
    next_stops["Perivale"] = {"central": ["Hanger Lane", "Greenford"]}
    next_stops["Piccadilly Circus"] = {"bakerloo": ["Charing Cross", "Oxford Circus"], "piccadilly": ["Leicester Square", "Green Park"]}
    next_stops["Pimlico"] = {"victoria": ["Vauxhall", "Victoria"]}
    next_stops["Pinner"] = {"metropolitan": ["Northwood Hills", "North Harrow"]}
    next_stops["Plaistow"] = {"district": ["Upton Park", "West Ham"], "hammersmith-city": ["Upton Park", "West Ham"]}
    next_stops["Preston Road"] = {"metropolitan": ["Northwick Park", "Wembley Park"]}
    next_stops["Putney Bridge"] = {"district": ["East Putney", "Parsons Green"]}
    next_stops["Queen's Park"] = {"bakerloo": ["Kilburn Park", "Kensal Green"]}
    next_stops["Queensbury"] = {"jubilee": ["Kingsbury", "Canons Park"]}
    next_stops["Queensway"] = {"central": ["Lancaster Gate", "Notting Hill Gate"]}
    next_stops["Ravenscourt Park"] = {"district": ["Stamford Brook", "Hammersmith (Dist&Picc Line)"]}
    next_stops["Rayners Lane"] = {"metropolitan": ["Eastcote", "West Harrow"], "piccadilly": ["Eastcote", "South Harrow"]}
    next_stops["Redbridge"] = {"central": ["Gants Hill", "Wanstead"]}
    next_stops["Regent's Park"] = {"bakerloo": ["Oxford Circus", "Baker Street"]}
    next_stops["Richmond"] = {"district": ["Kew Gardens"]}
    next_stops["Rickmansworth"] = {"metropolitan": ["Chorleywood", "Moor Park"]}
    next_stops["Roding Valley"] = {"central": ["Chigwell", "Woodford"]}
    next_stops["Royal Oak"] = {"circle": ["Paddington (H&C Line)", "Westbourne Park"], "hammersmith-city": ["Paddington (H&C Line)", "Westbourne Park"]}
    next_stops["Ruislip"] = {"metropolitan": ["Ruislip Manor", "Ickenham"], "piccadilly": ["Ruislip Manor", "Ickenham"]}
    next_stops["Ruislip Gardens"] = {"central": ["South Ruislip", "West Ruislip"]}
    next_stops["Ruislip Manor"] = {"metropolitan": ["Eastcote", "Ruislip"], "piccadilly": ["Eastcote", "Ruislip"]}
    next_stops["Russell Square"] = {"piccadilly": ["Holborn", "King's Cross St. Pancras"]}
    next_stops["Seven Sisters"] = {"victoria": ["Tottenham Hale", "Finsbury Park"]}
    next_stops["Shepherd's Bush (Central)"] = {"central": ["White City", "Holland Park"]}
    next_stops["Shepherd's Bush Market"] = {"circle": ["Goldhawk Road", "Wood Lane"], "hammersmith-city": ["Goldhawk Road", "Wood Lane"]}
    next_stops["Sloane Square"] = {"district": ["South Kensington", "Victoria"], "circle": ["South Kensington", "Victoria"]}
    next_stops["Snaresbrook"] = {"central": ["South Woodford", "Leytonstone"]}
    next_stops["South Ealing"] = {"piccadilly": ["Acton Town", "Northfields"]}
    next_stops["South Harrow"] = {"piccadilly": ["Sudbury Hill", "Rayners Lane"]}
    next_stops["South Kensington"] = {"district": ["Gloucester Road", "Sloane Square"], "circle": ["Gloucester Road", "Sloane Square"], "piccadilly": ["Gloucester Road", "Knightsbridge"]}
    next_stops["South Kenton"] = {"bakerloo": ["North Wembley", "Kenton"]}
    next_stops["South Ruislip"] = {"central": ["Northolt", "Ruislip Gardens"]}
    next_stops["South Wimbledon"] = {"northern": ["Colliers Wood", "Morden"]}
    next_stops["South Woodford"] = {"central": ["Snaresbrook", "Woodford"]}
    next_stops["Southfields"] = {"district": ["Wimbledon Park", "East Putney"]}
    next_stops["Southgate"] = {"piccadilly": ["Oakwood", "Arnos Grove"]}
    next_stops["Southwark"] = {"jubilee": ["Waterloo", "London Bridge"]}
    next_stops["St. James's Park"] = {"circle": ["Westminster", "Victoria"], "district": ["Westminster", "Victoria"]}
    next_stops["St. John's Wood"] = {"jubilee": ["Baker Street", "Swiss Cottage"]}
    next_stops["St. Paul's"] = {"central": ["Chancery Lane", "Bank"]}
    next_stops["Stamford Brook"] = {"district": ["Turnham Green", "Ravenscourt Park"]}
    next_stops["Stanmore"] = {"jubilee": ["Canons Park"]}
    next_stops["Stepney Green"] = {"district": ["Mile End", "Whitechapel"], "hammersmith-city": ["Mile End", "Whitechapel"]}
    next_stops["Stockwell"] = {"northern": ["Oval", "Clapham North"] , "victoria": ["Vauxhall", "Brixton"]}
    next_stops["Stonebridge Park"] = {"bakerloo": ["Wembley Central", "Harlesden"]}
    next_stops["Stratford"] = {"central": ["Leyton", "Mile End"], "jubilee": ["West Ham"]}
    next_stops["Sudbury Hill"] = {"piccadilly": ["Sudbury Town", "South Harrow"]}
    next_stops["Sudbury Town"] = {"piccadilly": ["Sudbury Hill", "Alperton"]}
    next_stops["Swiss Cottage"] = {"jubilee": ["Finchley Road", "St. John's Wood"]}
    next_stops["Temple"] = {"circle": ["Embankment", "Blackfriars"], "district": ["Embankment", "Blackfriars"]}
    next_stops["Theydon Bois"] = {"central": ["Epping", "Debden"]}
    next_stops["Tooting Bec"] = {"northern": ["Balham", "Tooting Broadway"]}
    next_stops["Tooting Broadway"] = {"northern": ["Tooting Bec", "Colliers Wood"]}
    next_stops["Tottenham Court Road"] = {"central": ["Oxford Circus", "Holborn"], "northern": ["Goodge Street", "Leicester Square"]}
    next_stops["Tottenham Hale"] = {"victoria": ["Blackhorse Road", "Seven Sisters"]}
    next_stops["Totteridge & Whetstone"] = {"northern": ["High Barnet", "Woodside Park"]}
    next_stops["Tower Hill"] = {"circle": ["Monument", "Aldgate"], "district": ["Monument", "Aldgate East"]}
    next_stops["Tufnell Park"] = {"northern": ["Kentish Town", "Archway"]}
    next_stops["Turnham Green"] = {"district": ["Chiswick Park", "Stamford Brook", "Gunnersbury"], "piccadilly": ["Acton Town", "Hammersmith (Dist&Picc Line)"]}
    next_stops["Turnpike Lane"] = {"piccadilly": ["Wood Green", "Manor House"]}
    next_stops["Upminster"] = {"district": ["Upminster Bridge"]}
    next_stops["Upminster Bridge"] = {"district": ["Hornchurch", "Upminster"]}
    next_stops["Upney"] = {"district": ["Barking", "Becontree"]}
    next_stops["Upton Park"] = {"district": ["Plaistow", "East Ham"], "hammersmith-city": ["Plaistow", "East Ham"]}
    next_stops["Uxbridge"] = {"metropolitan": ["Hillingdon"], "piccadilly": ["Hillingdon"]}
    next_stops["Vauxhall"] = {"victoria": ["Stockwell", "Pimlico"]}
    next_stops["Victoria"] = {"district": ["Sloane Square", "St. James's Park"], "circle": ["Sloane Square", "St. James's Park"], "victoria": ["Pimlico", "Green Park"]}
    next_stops["Walthamstow Central"] = {"victoria": ["Blackhorse Road"]}
    next_stops["Wanstead"] = {"central": ["Redbridge", "Leytonstone"]}
    next_stops["Warren Street"] = {"northern": ["Goodge Street", "Euston"], "victoria": ["Euston", "Oxford Circus"]}
    next_stops["Warwick Avenue"] = {"bakerloo": ["Maida Vale", "Paddington"]}
    next_stops["Waterloo"] = {"bakerloo": ["Lambeth North", "Embankment"], "jubilee": ["Southwark", "Westminster"], "northern": ["Kennington", "Embankment"], "waterloo-city": ["Bank"]}
    next_stops["Watford"] = {"metropolitan": ["Croxley"]}
    next_stops["Wembley Central"] = {"bakerloo": ["North Wembley", "Stonebridge Park"]}
    next_stops["Wembley Park"] = {"jubilee": ["Kingsbury", "Neasden"], "metropolitan": ["Preston Road", "Finchley Road", "Harrow-on-the-Hill"]}
    next_stops["West Acton"] = {"central": ["Ealing Broadway", "North Acton"]}
    next_stops["West Brompton"] = {"district": ["Fulham Broadway", "Earl's Court"]}
    next_stops["West Finchley"] = {"northern": ["Woodside Park", "Finchley Central"]}
    next_stops["West Ham"] = {"district": ["Plaistow", "Bromley-by-Bow"], "hammersmith-city": ["Plaistow", "Bromley-by-Bow"], "jubilee": ["Canning Town", "Stratford"]}
    next_stops["West Hampstead"] = {"jubilee": ["Finchley Road", "Kilburn"]}
    next_stops["West Harrow"] = {"metropolitan": ["Rayners Lane", "Harrow-on-the-Hill"]}
    next_stops["West Kensington"] = {"district": ["Barons Court", "Earl's Court"]}
    next_stops["West Ruislip"] = {"central": ["Ruislip Gardens"]}
    next_stops["Westbourne Park"] = {"circle": ["Royal Oak", "Ladbroke Grove"], "hammersmith-city": ["Royal Oak", "Ladbroke Grove"]}
    next_stops["Westminster"] = {"circle": ["St. James's Park", "Embankment"], "district": ["St. James's Park", "Embankment"], "jubilee": ["Waterloo", "Green Park"]}
    next_stops["White City"] = {"central": ["Shepherd's Bush (Central)", "East Acton"]}
    next_stops["Whitechapel"] = {"district": ["Stepney Green", "Aldgate East"], "hammersmith-city": ["Stepney Green", "Aldgate East"]}
    next_stops["Willesden Green"] = {"jubilee": ["Dollis Hill", "Kilburn"]}
    next_stops["Willesden Junction"] = {"bakerloo": ["Harlesden", "Kensal Green"]}
    next_stops["Wimbledon"] = {"district": ["Wimbledon Park"]}
    next_stops["Wimbledon Park"] = {"district": ["Southfields", "Wimbledon"]}
    next_stops["Wood Green"] = {"piccadilly": ["Turnpike Lane", "Bounds Green"]}
    next_stops["Wood Lane"] = {"circle": ["Latimer Road", "Shepherd's Bush Market"], "hammersmith-city": ["Latimer Road", "Shepherd's Bush Market"]}
    next_stops["Woodford"] = {"central": ["South Woodford", "Roding Valley", "Buckhurst Hill"]}
    next_stops["Woodside Park"] = {"northern": ["West Finchley", "Totteridge & Whetstone"]}
except Exception as e:
    print(e)

